@startuml



class "Spot" as spot {
    systolic
    diastolic
    unit
    timestamp
}


class "Average" as avg {
    systolic
    diastolic
    unit
    period
    count
}

avg "0..*" o-down- "0..*" spot : used

@enduml