@startuml


class "Spot" as spot {
    systolic
    diastolic
    unit
    timestamp
}


class "Calculated" as calc {
    systolic
    diastolic
    unit
    period
    count
    function
}

calc "0..*" o-right- "0..*" spot : "      used        "

@enduml