@startuml

class "**[[StructureDefinition-BloodPressure.html Blood Pressure]]**" as bp {
    identifier
    interpretation: code
    location: code
    positionOfBody: code
    positionOfArm: code
    method: code
    exertion: code|quantity
    consciousness: code
    tilt: integer
    dateTime: instant|period
    comment: string
}

package "Measurement" {
    abstract class "Blood Pressure Value" as bpv {
        value: integer
        unit = mm[Hg]
        referenceRange: range
        interpretation: code
    }

    class "Reference Range" as rr {
        low : integer
        high: integer
        age: range
    }
}

class "**Systolic BP**" as syst
class "**Diastolic BP**" as diast

class "Device" as dev {
    type: code
    cuffType: code
    cuffSize: code
    serialNumber: string|UDI
}

package "Calculation (1 value)" as calc1 {
    class "Pulse Pressure" as pbp
    class "Mean Arterial Pressure" as mabp
}

package "Calculation (2 values)" as calc2 {
    class "Ambulatory BP" as ambbp
    class "Average"
    class "Mean"
    class "Min"
    class "Max"
}

package "Other Relevant Concepts" {
    class "Body Weight" as bw #cfc
    Note right of bw
    necessary to
    interpret
    the measurement
    end Note
    class "Medication" as med #cfc
    class "Exertion" as exer #cfc

}


package "Participation" {
    abstract class "Role" as rol #88f {
        type: code
    }
    class "Author" as a #88f
    class "Performer" as p #88f
    Note right of p
    normally a physician,
    but could also
    be the patient
    end Note
    class "Recorder" as r #88f

    class "Person" as pers #88f {
        identifier
        name
        gender
        dob
    }
    rol "0..*" -left- "1" pers

    class "Subject" as s #88f
    Note left of s
    normally
    the patient
    end Note

    rol <|-- a
    rol <|-- p
    rol <|-- r
    rol <|-- s
}


bpv <|-up- syst
bpv <|-up- diast
bpv <|-down- mabp
bpv <|-down- pbp
bpv "1" *-right- "1" rr

bp <|-right- ambbp

bp -up- "0..1" a
bp -up- "0..1" p
bp -up- "0..1" r
bp -up- "1" s
bp -- bw
bp -right- "0..1" exer
bp -right- "0..*" med
bp "1" -left- "1" dev

bp *-- "1" syst
bp *-- "0..1" diast

@enduml