@startmindmap

'skinparam svgDimensionStyle false

title Blood Pressure Dimensions

+ **Dimensions**

++ Invasive vs. Non-invasive
++ Measured vs. Calculated
+++_ Spot
+++_ Average
++ Context Setting
+++_ definition of certain parameters
++ executing Protocols
+++_ sequence of specific measurements
++ Interpretation Dependency
+++_ Medication
+++_ Level of current or former physical Exertion
++ Performer
+++_ Patient: self-measurements
+++_ Physician: "professional" meeasurements

@endmindmap