@startmindmap

skinparam svgDimensionStyle false

title Blood Pressure related Concepts to be considered

legend
Legend:
<img icon_modifier_extension_complex.png> relevant context details
<img icon_page_n_i.gif> addt'l information
end legend

+ **Blood** \n**Pressure**

--[#ff8] measured value
---[#fcc] systolic
----[#cff] DT: integer
-----_ range: 0-400
----[#fcc] reference range
-----_ range: 0-400
-----_ age: integer
---[#fcc] diastolic
----[#cff] DT: integer
-----_ range: 0-400
-----_ age: integer
----[#fcc] reference range
-----_ range: 0-400
---[#fcc] unit
----[#cff] DT: code
-----_ mmHg
---[#fcc] reference range
----_ age: integer
----_ gender: code
---[#fcc] interpretation
----[#cff] DT: code
-----_ critical low
-----_ low
-----_ normal
-----_ high
-----_ critical high

--[#ff8] calculated value
---[#fcc] meanArterialPressure
----[#cff] DT: integer
-----_ range: 60-100
---- duration
-----[#cff] DT: code
------_ 1h
------_ 8h
------_ 10h
------_ 12h
------_ 24h
---- calculation
-----[#cff] DT: code
------_ ballanced
------_ algorithm
----[#fcc] reference range
---[#fcc] pulsePressure
----[#cff] DT: integer
-----_ range: 0-1000
----[#fcc] reference range

--[#cfc]  <img icon_modifier_extension_complex.png> other relevant concepts
---[#cfc] <img icon_modifier_extension_complex.png> medication
----_ influences the results \nof the measurement
----[#cff] boolean
----[#fcc] MedicationAdministration
---[#cfc] <img icon_modifier_extension_complex.png> current/former exercise assocation
----[#cff] DT: code
-----_ sleeping
-----_ sitting
-----_ walking
------_ slow
------_ normal
------_ fast
-----_ jogging
------_ slow
------_ normal
------_ fast
-----_ running
------_ slow
------_ normal
------_ fast
-----_ biking
----[#cff] DT: PQ
-----_ Watts
---[#cfc] timing
----_ pre
----_ during
----_ post
---[#cfc] <img icon_modifier_extension_complex.png> body weight
----_ relevant for a correct interpretation
---[#cfc] <img icon_modifier_extension_complex.png> pulse
----[#cff] PQ
----[#cff] Reference
---[#cfc] <img icon_modifier_extension_complex.png> anaesthesia
----[#cff] DT: code
-----_ before
-----_ during
-----_ after
----[#fcc] anaesthetica

++[#ff8] administrative
+++[#fcc] identifier
+++[#fcc] observedDateTime
++++[#cff] DT: instant | dateTime | period
+++[#fcc] recordedDateTime
++++[#cff] DT: dateTime

+++[#88f] involved persons
++++[#88f] subject
+++++_ age
+++++_ gender
++++[#88f] author
++++[#88f] performer
++++[#88f] recorder

+++[#ff8] device
++++_ type
++++_ validated?
++++_ ...

++[#ff8] <img icon_modifier_extension_complex.png> context
+++[#ff8] <img icon_modifier_extension_complex.png> positioning of body
++++[#cff] DT: code
+++++_ sitting
+++++_ standing
+++++_ reclining
+++++_ lying
++++++_ lying on back
++++++_ lying with tilt to left
+++[#ff8] <img icon_modifier_extension_complex.png> positioning of arm
++++[#cff] DT: code
+++++_ down
+++++_ up
+++[#ff8] <img icon_modifier_extension_complex.png> cuff size
++++[#cff] DT: code/integer
+++[#ff8] <img icon_modifier_extension_complex.png> method
++++[#cff] DT: code

++[#ff8] <img icon_page_n_i.gif> protocol
+++[#ff8] executable protocol
++++_ SPRINT
++++_ NHANES 
++++_ stress test
++++_ hypertension management
++++_ ...
+++[#ff8] duration of measurement
++++[#cff] range
+++++[#cff] start: timestamp
+++++[#cff] end: timestamp
++++[#cff] DT: code
+++++_ spot
+++++_ 1h
+++++_ 8h
+++++_ 10h
+++++_ 12h
+++++_ 24h
+++[#ff8] location at body
++++[#cff] DT: code
+++++[#f88] extern
++++++_ arm
+++++++_ right
+++++++_ left
++++++_ wrist
++++++_ ankle
++++++_ finger
++++++_ toe
+++++[#f88] intern
++++++_ left heart
++++++_ right heart
++++++_ radialis artery
++++++_ coronary artery
+++[#ff8] measurement setting
++++[#cff] DT: code
+++++_ physician office / clinic / hospital / ED
+++++_ dwelling / home
+++[#ff8] tilt (degree)
++++[#cff] DT: integer
+++[#ff8] aspiration
++++_ expiration
++++_ inspiration
+++[#ff8] event
++++_ normal
++++_ stressed by someone/thing
+++++_ physician
+++++_ bear/tiger/snake
+++[#ff8] <img icon_page_n_i.gif> cuff type
++++[#cff] DT: code
+++[#ff8] consciousness
++++[#cff] DT: code
+++++_ awake
+++++_ unconscious
+++++_ sleeping

++[#ff8] comment
+++[#cff] DT: text

@endmindmap