@startmindmap

'skinparam svgDimensionStyle false

title Blood Pressure Dimensions

+ **Dimensions**

++ Invasive vs. Non-invasive
++ Measured vs. Calculated
++ Spot vs. Average
++ Level of current or former physical Exertion
++ Performer (patient vs. physician)

@endmindmap