@startuml


abstract class "Value" as value {
    value
    unit
    timestamp
}

abstract class "Reference Range" as range {
    low
    high
}

value "1" *-right- "1" range :  "             "

package "measured" as measured {


class "Systolic" as syst {
}

class "Diastolic" as diast {
}
}

package "calculated" as calc {

class "Pulse Pressure" as pulse {
    formula
}

}

package "finding: integrated result" as integr {

class "Mean Arterial Pressure" as mean {
    formula
}


}


syst "0..1" -- pulse
diast "0..1" -- pulse

syst "0..*" -- mean
diast "0..*" -- mean


value <|-- syst
value <|-- diast
value <|-- pulse
value <|-- mean



@enduml