@startuml

title "Representation in FHIR: ITS"

package "Patient Resource" {
    class "Patient" as pat {
        identifier
        name
        gender
        dob
    }

}

package "Observation Resource: BP" #dfd {
    class "MainObservationData" as obs {
        identifier
        status
        category
        code
        effectiveDateTime
        note
        bodySite
        method
    }

    class "Component: systolic" as syst {
        code
        value
        dataAbsentReason
        interpretation
        referenceRange
    }

    class "Component: diastolic" as diast {
        code
        value
        dataAbsentReason
        interpretation
        referenceRange
    }

    obs *.. "0..1" syst
    obs *.. "0..1" diast
}

package "Observation Resource: Exertion" #bfb {
    class "MainObservationData" as ex {
        identifier
        status
        category
        code
        value
        interpretation
        effectiveDateTime
        note
    }
}

package "Observation Resource: Body Weight" #bfb {
    class "MainObservationData" as bw {
        identifier
        status
        category
        code
        value
        interpretation
        effectiveDateTime
        note
    }
}

package "MedicationStatement" {
    class "MedicationStatement" as medstat {
        identifier
        status
        category
        effectiveDateTime
    }
}

package "Medication" {
    class "Medication" as med {
        identifier
        code
        status
        doseForm
    }

    class "Ingredient" as ing {
        item
        isActive
        strength
    }

    med .left.> ing : ingredient
}

package "PractitionerRole Resource" {
    class "PractitionerRole" as role {
        identifier
        active
        code
        period
    }
}

package "Practitioner Resource" {
    class "Practitioner" as pract {
        identifier
        name
    }

}

package "Resource Device" {
    class "Device" as dev {
        identifier
        displayName
        status
        name[]
        modelNumber
        serialNumber
        category
        type
    }
}

diamond xy


obs -up-> "0..1" pat : subject
obs -right-> xy
xy -up-> "0..*" pat : performer (self)
xy -right-> "0..*" role : performer (professional)
obs --> dev

ex -left-> "0..1" pat : subject

medstat -down-> "0..1" pat : subject
medstat -right-> med : medication

bw ---> pat : subject

role "1" -right-> "0..1" pract

@enduml